// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: william/admin/v1/admin.proto

package adminpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ChatSummary represents aggregated chat information
type ChatSummary struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	ChatId        int64                  `protobuf:"varint,2,opt,name=chat_id,json=chatId,proto3" json:"chat_id,omitempty"`
	Summary       string                 `protobuf:"bytes,3,opt,name=summary,proto3" json:"summary,omitempty"`
	Topics        map[string]string      `protobuf:"bytes,4,rep,name=topics,proto3" json:"topics,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	NextEvents    *string                `protobuf:"bytes,5,opt,name=next_events,json=nextEvents,proto3,oneof" json:"next_events,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChatSummary) Reset() {
	*x = ChatSummary{}
	mi := &file_william_admin_v1_admin_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChatSummary) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatSummary) ProtoMessage() {}

func (x *ChatSummary) ProtoReflect() protoreflect.Message {
	mi := &file_william_admin_v1_admin_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatSummary.ProtoReflect.Descriptor instead.
func (*ChatSummary) Descriptor() ([]byte, []int) {
	return file_william_admin_v1_admin_proto_rawDescGZIP(), []int{0}
}

func (x *ChatSummary) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *ChatSummary) GetChatId() int64 {
	if x != nil {
		return x.ChatId
	}
	return 0
}

func (x *ChatSummary) GetSummary() string {
	if x != nil {
		return x.Summary
	}
	return ""
}

func (x *ChatSummary) GetTopics() map[string]string {
	if x != nil {
		return x.Topics
	}
	return nil
}

func (x *ChatSummary) GetNextEvents() string {
	if x != nil && x.NextEvents != nil {
		return *x.NextEvents
	}
	return ""
}

func (x *ChatSummary) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *ChatSummary) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

// UserSummary represents user behavior analysis
type UserSummary struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	ChatId        int64                  `protobuf:"varint,2,opt,name=chat_id,json=chatId,proto3" json:"chat_id,omitempty"`
	UserId        int64                  `protobuf:"varint,3,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Likes         map[string]string      `protobuf:"bytes,4,rep,name=likes,proto3" json:"likes,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Dislikes      map[string]string      `protobuf:"bytes,5,rep,name=dislikes,proto3" json:"dislikes,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Competencies  map[string]string      `protobuf:"bytes,6,rep,name=competencies,proto3" json:"competencies,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Traits        *string                `protobuf:"bytes,7,opt,name=traits,proto3,oneof" json:"traits,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserSummary) Reset() {
	*x = UserSummary{}
	mi := &file_william_admin_v1_admin_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserSummary) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserSummary) ProtoMessage() {}

func (x *UserSummary) ProtoReflect() protoreflect.Message {
	mi := &file_william_admin_v1_admin_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserSummary.ProtoReflect.Descriptor instead.
func (*UserSummary) Descriptor() ([]byte, []int) {
	return file_william_admin_v1_admin_proto_rawDescGZIP(), []int{1}
}

func (x *UserSummary) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UserSummary) GetChatId() int64 {
	if x != nil {
		return x.ChatId
	}
	return 0
}

func (x *UserSummary) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *UserSummary) GetLikes() map[string]string {
	if x != nil {
		return x.Likes
	}
	return nil
}

func (x *UserSummary) GetDislikes() map[string]string {
	if x != nil {
		return x.Dislikes
	}
	return nil
}

func (x *UserSummary) GetCompetencies() map[string]string {
	if x != nil {
		return x.Competencies
	}
	return nil
}

func (x *UserSummary) GetTraits() string {
	if x != nil && x.Traits != nil {
		return *x.Traits
	}
	return ""
}

func (x *UserSummary) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *UserSummary) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

// Chat summary requests and responses
type GetChatSummaryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ChatIds       []int64                `protobuf:"varint,1,rep,packed,name=chat_ids,json=chatIds,proto3" json:"chat_ids,omitempty"` // Can be one or multiple chat IDs
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetChatSummaryRequest) Reset() {
	*x = GetChatSummaryRequest{}
	mi := &file_william_admin_v1_admin_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetChatSummaryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetChatSummaryRequest) ProtoMessage() {}

func (x *GetChatSummaryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_william_admin_v1_admin_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetChatSummaryRequest.ProtoReflect.Descriptor instead.
func (*GetChatSummaryRequest) Descriptor() ([]byte, []int) {
	return file_william_admin_v1_admin_proto_rawDescGZIP(), []int{2}
}

func (x *GetChatSummaryRequest) GetChatIds() []int64 {
	if x != nil {
		return x.ChatIds
	}
	return nil
}

type GetChatSummaryResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Summaries     []*ChatSummary         `protobuf:"bytes,1,rep,name=summaries,proto3" json:"summaries,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetChatSummaryResponse) Reset() {
	*x = GetChatSummaryResponse{}
	mi := &file_william_admin_v1_admin_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetChatSummaryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetChatSummaryResponse) ProtoMessage() {}

func (x *GetChatSummaryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_william_admin_v1_admin_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetChatSummaryResponse.ProtoReflect.Descriptor instead.
func (*GetChatSummaryResponse) Descriptor() ([]byte, []int) {
	return file_william_admin_v1_admin_proto_rawDescGZIP(), []int{3}
}

func (x *GetChatSummaryResponse) GetSummaries() []*ChatSummary {
	if x != nil {
		return x.Summaries
	}
	return nil
}

// User summary requests and responses
type GetUserSummaryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ChatId        int64                  `protobuf:"varint,1,opt,name=chat_id,json=chatId,proto3" json:"chat_id,omitempty"`
	UserIds       []int64                `protobuf:"varint,2,rep,packed,name=user_ids,json=userIds,proto3" json:"user_ids,omitempty"` // Can be one or multiple user IDs
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserSummaryRequest) Reset() {
	*x = GetUserSummaryRequest{}
	mi := &file_william_admin_v1_admin_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserSummaryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserSummaryRequest) ProtoMessage() {}

func (x *GetUserSummaryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_william_admin_v1_admin_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserSummaryRequest.ProtoReflect.Descriptor instead.
func (*GetUserSummaryRequest) Descriptor() ([]byte, []int) {
	return file_william_admin_v1_admin_proto_rawDescGZIP(), []int{4}
}

func (x *GetUserSummaryRequest) GetChatId() int64 {
	if x != nil {
		return x.ChatId
	}
	return 0
}

func (x *GetUserSummaryRequest) GetUserIds() []int64 {
	if x != nil {
		return x.UserIds
	}
	return nil
}

type GetUserSummaryResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Summaries     []*UserSummary         `protobuf:"bytes,1,rep,name=summaries,proto3" json:"summaries,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserSummaryResponse) Reset() {
	*x = GetUserSummaryResponse{}
	mi := &file_william_admin_v1_admin_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserSummaryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserSummaryResponse) ProtoMessage() {}

func (x *GetUserSummaryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_william_admin_v1_admin_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserSummaryResponse.ProtoReflect.Descriptor instead.
func (*GetUserSummaryResponse) Descriptor() ([]byte, []int) {
	return file_william_admin_v1_admin_proto_rawDescGZIP(), []int{5}
}

func (x *GetUserSummaryResponse) GetSummaries() []*UserSummary {
	if x != nil {
		return x.Summaries
	}
	return nil
}

// Manual summarization requests and responses
type TriggerSummarizationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ChatId        int64                  `protobuf:"varint,1,opt,name=chat_id,json=chatId,proto3" json:"chat_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TriggerSummarizationRequest) Reset() {
	*x = TriggerSummarizationRequest{}
	mi := &file_william_admin_v1_admin_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TriggerSummarizationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TriggerSummarizationRequest) ProtoMessage() {}

func (x *TriggerSummarizationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_william_admin_v1_admin_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TriggerSummarizationRequest.ProtoReflect.Descriptor instead.
func (*TriggerSummarizationRequest) Descriptor() ([]byte, []int) {
	return file_william_admin_v1_admin_proto_rawDescGZIP(), []int{6}
}

func (x *TriggerSummarizationRequest) GetChatId() int64 {
	if x != nil {
		return x.ChatId
	}
	return 0
}

type TriggerSummarizationResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       *string                `protobuf:"bytes,2,opt,name=message,proto3,oneof" json:"message,omitempty"`
	EventId       *string                `protobuf:"bytes,3,opt,name=event_id,json=eventId,proto3,oneof" json:"event_id,omitempty"` // Event ID for tracking execution
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TriggerSummarizationResponse) Reset() {
	*x = TriggerSummarizationResponse{}
	mi := &file_william_admin_v1_admin_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TriggerSummarizationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TriggerSummarizationResponse) ProtoMessage() {}

func (x *TriggerSummarizationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_william_admin_v1_admin_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TriggerSummarizationResponse.ProtoReflect.Descriptor instead.
func (*TriggerSummarizationResponse) Descriptor() ([]byte, []int) {
	return file_william_admin_v1_admin_proto_rawDescGZIP(), []int{7}
}

func (x *TriggerSummarizationResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *TriggerSummarizationResponse) GetMessage() string {
	if x != nil && x.Message != nil {
		return *x.Message
	}
	return ""
}

func (x *TriggerSummarizationResponse) GetEventId() string {
	if x != nil && x.EventId != nil {
		return *x.EventId
	}
	return ""
}

var File_william_admin_v1_admin_proto protoreflect.FileDescriptor

const file_william_admin_v1_admin_proto_rawDesc = "" +
	"\n" +
	"\x1cwilliam/admin/v1/admin.proto\x12\x10william.admin.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\xfa\x02\n" +
	"\vChatSummary\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x17\n" +
	"\achat_id\x18\x02 \x01(\x03R\x06chatId\x12\x18\n" +
	"\asummary\x18\x03 \x01(\tR\asummary\x12A\n" +
	"\x06topics\x18\x04 \x03(\v2).william.admin.v1.ChatSummary.TopicsEntryR\x06topics\x12$\n" +
	"\vnext_events\x18\x05 \x01(\tH\x00R\n" +
	"nextEvents\x88\x01\x01\x129\n" +
	"\n" +
	"created_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\x1a9\n" +
	"\vTopicsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01B\x0e\n" +
	"\f_next_events\"\x83\x05\n" +
	"\vUserSummary\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x17\n" +
	"\achat_id\x18\x02 \x01(\x03R\x06chatId\x12\x17\n" +
	"\auser_id\x18\x03 \x01(\x03R\x06userId\x12>\n" +
	"\x05likes\x18\x04 \x03(\v2(.william.admin.v1.UserSummary.LikesEntryR\x05likes\x12G\n" +
	"\bdislikes\x18\x05 \x03(\v2+.william.admin.v1.UserSummary.DislikesEntryR\bdislikes\x12S\n" +
	"\fcompetencies\x18\x06 \x03(\v2/.william.admin.v1.UserSummary.CompetenciesEntryR\fcompetencies\x12\x1b\n" +
	"\x06traits\x18\a \x01(\tH\x00R\x06traits\x88\x01\x01\x129\n" +
	"\n" +
	"created_at\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\t \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\x1a8\n" +
	"\n" +
	"LikesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\x1a;\n" +
	"\rDislikesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\x1a?\n" +
	"\x11CompetenciesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01B\t\n" +
	"\a_traits\"2\n" +
	"\x15GetChatSummaryRequest\x12\x19\n" +
	"\bchat_ids\x18\x01 \x03(\x03R\achatIds\"U\n" +
	"\x16GetChatSummaryResponse\x12;\n" +
	"\tsummaries\x18\x01 \x03(\v2\x1d.william.admin.v1.ChatSummaryR\tsummaries\"K\n" +
	"\x15GetUserSummaryRequest\x12\x17\n" +
	"\achat_id\x18\x01 \x01(\x03R\x06chatId\x12\x19\n" +
	"\buser_ids\x18\x02 \x03(\x03R\auserIds\"U\n" +
	"\x16GetUserSummaryResponse\x12;\n" +
	"\tsummaries\x18\x01 \x03(\v2\x1d.william.admin.v1.UserSummaryR\tsummaries\"6\n" +
	"\x1bTriggerSummarizationRequest\x12\x17\n" +
	"\achat_id\x18\x01 \x01(\x03R\x06chatId\"\x90\x01\n" +
	"\x1cTriggerSummarizationResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x1d\n" +
	"\amessage\x18\x02 \x01(\tH\x00R\amessage\x88\x01\x01\x12\x1e\n" +
	"\bevent_id\x18\x03 \x01(\tH\x01R\aeventId\x88\x01\x01B\n" +
	"\n" +
	"\b_messageB\v\n" +
	"\t_event_id2\xcf\x02\n" +
	"\fAdminService\x12c\n" +
	"\x0eGetChatSummary\x12'.william.admin.v1.GetChatSummaryRequest\x1a(.william.admin.v1.GetChatSummaryResponse\x12c\n" +
	"\x0eGetUserSummary\x12'.william.admin.v1.GetUserSummaryRequest\x1a(.william.admin.v1.GetUserSummaryResponse\x12u\n" +
	"\x14TriggerSummarization\x12-.william.admin.v1.TriggerSummarizationRequest\x1a..william.admin.v1.TriggerSummarizationResponseB(Z&github.com/xdefrag/william/pkg/adminpbb\x06proto3"

var (
	file_william_admin_v1_admin_proto_rawDescOnce sync.Once
	file_william_admin_v1_admin_proto_rawDescData []byte
)

func file_william_admin_v1_admin_proto_rawDescGZIP() []byte {
	file_william_admin_v1_admin_proto_rawDescOnce.Do(func() {
		file_william_admin_v1_admin_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_william_admin_v1_admin_proto_rawDesc), len(file_william_admin_v1_admin_proto_rawDesc)))
	})
	return file_william_admin_v1_admin_proto_rawDescData
}

var file_william_admin_v1_admin_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_william_admin_v1_admin_proto_goTypes = []any{
	(*ChatSummary)(nil),                  // 0: william.admin.v1.ChatSummary
	(*UserSummary)(nil),                  // 1: william.admin.v1.UserSummary
	(*GetChatSummaryRequest)(nil),        // 2: william.admin.v1.GetChatSummaryRequest
	(*GetChatSummaryResponse)(nil),       // 3: william.admin.v1.GetChatSummaryResponse
	(*GetUserSummaryRequest)(nil),        // 4: william.admin.v1.GetUserSummaryRequest
	(*GetUserSummaryResponse)(nil),       // 5: william.admin.v1.GetUserSummaryResponse
	(*TriggerSummarizationRequest)(nil),  // 6: william.admin.v1.TriggerSummarizationRequest
	(*TriggerSummarizationResponse)(nil), // 7: william.admin.v1.TriggerSummarizationResponse
	nil,                                  // 8: william.admin.v1.ChatSummary.TopicsEntry
	nil,                                  // 9: william.admin.v1.UserSummary.LikesEntry
	nil,                                  // 10: william.admin.v1.UserSummary.DislikesEntry
	nil,                                  // 11: william.admin.v1.UserSummary.CompetenciesEntry
	(*timestamppb.Timestamp)(nil),        // 12: google.protobuf.Timestamp
}
var file_william_admin_v1_admin_proto_depIdxs = []int32{
	8,  // 0: william.admin.v1.ChatSummary.topics:type_name -> william.admin.v1.ChatSummary.TopicsEntry
	12, // 1: william.admin.v1.ChatSummary.created_at:type_name -> google.protobuf.Timestamp
	12, // 2: william.admin.v1.ChatSummary.updated_at:type_name -> google.protobuf.Timestamp
	9,  // 3: william.admin.v1.UserSummary.likes:type_name -> william.admin.v1.UserSummary.LikesEntry
	10, // 4: william.admin.v1.UserSummary.dislikes:type_name -> william.admin.v1.UserSummary.DislikesEntry
	11, // 5: william.admin.v1.UserSummary.competencies:type_name -> william.admin.v1.UserSummary.CompetenciesEntry
	12, // 6: william.admin.v1.UserSummary.created_at:type_name -> google.protobuf.Timestamp
	12, // 7: william.admin.v1.UserSummary.updated_at:type_name -> google.protobuf.Timestamp
	0,  // 8: william.admin.v1.GetChatSummaryResponse.summaries:type_name -> william.admin.v1.ChatSummary
	1,  // 9: william.admin.v1.GetUserSummaryResponse.summaries:type_name -> william.admin.v1.UserSummary
	2,  // 10: william.admin.v1.AdminService.GetChatSummary:input_type -> william.admin.v1.GetChatSummaryRequest
	4,  // 11: william.admin.v1.AdminService.GetUserSummary:input_type -> william.admin.v1.GetUserSummaryRequest
	6,  // 12: william.admin.v1.AdminService.TriggerSummarization:input_type -> william.admin.v1.TriggerSummarizationRequest
	3,  // 13: william.admin.v1.AdminService.GetChatSummary:output_type -> william.admin.v1.GetChatSummaryResponse
	5,  // 14: william.admin.v1.AdminService.GetUserSummary:output_type -> william.admin.v1.GetUserSummaryResponse
	7,  // 15: william.admin.v1.AdminService.TriggerSummarization:output_type -> william.admin.v1.TriggerSummarizationResponse
	13, // [13:16] is the sub-list for method output_type
	10, // [10:13] is the sub-list for method input_type
	10, // [10:10] is the sub-list for extension type_name
	10, // [10:10] is the sub-list for extension extendee
	0,  // [0:10] is the sub-list for field type_name
}

func init() { file_william_admin_v1_admin_proto_init() }
func file_william_admin_v1_admin_proto_init() {
	if File_william_admin_v1_admin_proto != nil {
		return
	}
	file_william_admin_v1_admin_proto_msgTypes[0].OneofWrappers = []any{}
	file_william_admin_v1_admin_proto_msgTypes[1].OneofWrappers = []any{}
	file_william_admin_v1_admin_proto_msgTypes[7].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_william_admin_v1_admin_proto_rawDesc), len(file_william_admin_v1_admin_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_william_admin_v1_admin_proto_goTypes,
		DependencyIndexes: file_william_admin_v1_admin_proto_depIdxs,
		MessageInfos:      file_william_admin_v1_admin_proto_msgTypes,
	}.Build()
	File_william_admin_v1_admin_proto = out.File
	file_william_admin_v1_admin_proto_goTypes = nil
	file_william_admin_v1_admin_proto_depIdxs = nil
}
