// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.29.3
// source: william/admin/v1/admin.proto

package adminpb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	AdminService_GetChatSummary_FullMethodName       = "/william.admin.v1.AdminService/GetChatSummary"
	AdminService_GetUserSummary_FullMethodName       = "/william.admin.v1.AdminService/GetUserSummary"
	AdminService_TriggerSummarization_FullMethodName = "/william.admin.v1.AdminService/TriggerSummarization"
)

// AdminServiceClient is the client API for AdminService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// AdminService provides administrative operations for William bot
type AdminServiceClient interface {
	// GetChatSummary retrieves summaries for one or multiple chats
	GetChatSummary(ctx context.Context, in *GetChatSummaryRequest, opts ...grpc.CallOption) (*GetChatSummaryResponse, error)
	// GetUserSummary retrieves summaries for one or multiple users in a chat
	GetUserSummary(ctx context.Context, in *GetUserSummaryRequest, opts ...grpc.CallOption) (*GetUserSummaryResponse, error)
	// TriggerSummarization manually triggers summarization for a chat
	TriggerSummarization(ctx context.Context, in *TriggerSummarizationRequest, opts ...grpc.CallOption) (*TriggerSummarizationResponse, error)
}

type adminServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewAdminServiceClient(cc grpc.ClientConnInterface) AdminServiceClient {
	return &adminServiceClient{cc}
}

func (c *adminServiceClient) GetChatSummary(ctx context.Context, in *GetChatSummaryRequest, opts ...grpc.CallOption) (*GetChatSummaryResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetChatSummaryResponse)
	err := c.cc.Invoke(ctx, AdminService_GetChatSummary_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminServiceClient) GetUserSummary(ctx context.Context, in *GetUserSummaryRequest, opts ...grpc.CallOption) (*GetUserSummaryResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetUserSummaryResponse)
	err := c.cc.Invoke(ctx, AdminService_GetUserSummary_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminServiceClient) TriggerSummarization(ctx context.Context, in *TriggerSummarizationRequest, opts ...grpc.CallOption) (*TriggerSummarizationResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TriggerSummarizationResponse)
	err := c.cc.Invoke(ctx, AdminService_TriggerSummarization_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AdminServiceServer is the server API for AdminService service.
// All implementations must embed UnimplementedAdminServiceServer
// for forward compatibility.
//
// AdminService provides administrative operations for William bot
type AdminServiceServer interface {
	// GetChatSummary retrieves summaries for one or multiple chats
	GetChatSummary(context.Context, *GetChatSummaryRequest) (*GetChatSummaryResponse, error)
	// GetUserSummary retrieves summaries for one or multiple users in a chat
	GetUserSummary(context.Context, *GetUserSummaryRequest) (*GetUserSummaryResponse, error)
	// TriggerSummarization manually triggers summarization for a chat
	TriggerSummarization(context.Context, *TriggerSummarizationRequest) (*TriggerSummarizationResponse, error)
	mustEmbedUnimplementedAdminServiceServer()
}

// UnimplementedAdminServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAdminServiceServer struct{}

func (UnimplementedAdminServiceServer) GetChatSummary(context.Context, *GetChatSummaryRequest) (*GetChatSummaryResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetChatSummary not implemented")
}
func (UnimplementedAdminServiceServer) GetUserSummary(context.Context, *GetUserSummaryRequest) (*GetUserSummaryResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetUserSummary not implemented")
}
func (UnimplementedAdminServiceServer) TriggerSummarization(context.Context, *TriggerSummarizationRequest) (*TriggerSummarizationResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method TriggerSummarization not implemented")
}
func (UnimplementedAdminServiceServer) mustEmbedUnimplementedAdminServiceServer() {}
func (UnimplementedAdminServiceServer) testEmbeddedByValue()                      {}

// UnsafeAdminServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AdminServiceServer will
// result in compilation errors.
type UnsafeAdminServiceServer interface {
	mustEmbedUnimplementedAdminServiceServer()
}

func RegisterAdminServiceServer(s grpc.ServiceRegistrar, srv AdminServiceServer) {
	// If the following call pancis, it indicates UnimplementedAdminServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&AdminService_ServiceDesc, srv)
}

func _AdminService_GetChatSummary_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetChatSummaryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminServiceServer).GetChatSummary(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AdminService_GetChatSummary_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminServiceServer).GetChatSummary(ctx, req.(*GetChatSummaryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AdminService_GetUserSummary_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetUserSummaryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminServiceServer).GetUserSummary(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AdminService_GetUserSummary_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminServiceServer).GetUserSummary(ctx, req.(*GetUserSummaryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AdminService_TriggerSummarization_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TriggerSummarizationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminServiceServer).TriggerSummarization(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AdminService_TriggerSummarization_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminServiceServer).TriggerSummarization(ctx, req.(*TriggerSummarizationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// AdminService_ServiceDesc is the grpc.ServiceDesc for AdminService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AdminService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "william.admin.v1.AdminService",
	HandlerType: (*AdminServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetChatSummary",
			Handler:    _AdminService_GetChatSummary_Handler,
		},
		{
			MethodName: "GetUserSummary",
			Handler:    _AdminService_GetUserSummary_Handler,
		},
		{
			MethodName: "TriggerSummarization",
			Handler:    _AdminService_TriggerSummarization_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "william/admin/v1/admin.proto",
}
